---
- name: Install Libreswan package
  yum:
    name: libreswan
    update_cache: yes
  become: yes
  delegate_to: responder

- name: Start IPSEC service
  systemd:
    name: ipsec
    state: started
    enabled: yes
  become: yes
  delegate_to: responder

- name: Push Libreswan configuration file to responder
  template:
    src: "{{ lookup('first_found', params) }}"
    dest: "/etc/ipsec.d/{{ cloud_vpn_name }}-{{ cloud_vpn_initiator_public_ip | to_uuid }}.conf"
  vars:
    params:
      files:
        - "configure_vpn_{{ cloud_vpn_mode }}_{{ cloud_vpn_routing }}.j2"
      paths:
        - "templates/cloud_vpn/providers/rhel/responder/{{ cloud_vpn_responder_provider }}"
        - templates/cloud_vpn/providers/rhel/responder
  become: yes
  delegate_to: responder

- name: Push Libreswan secrets file to responder
  template:
    src:  "{{ lookup('first_found', params) }}"
    dest: "/etc/ipsec.d/{{ cloud_vpn_name }}-{{ cloud_vpn_initiator_public_ip | to_uuid }}.secrets"
  vars:
    params:
      files:
        - "configure_psk_{{ cloud_vpn_mode }}.j2"
      paths:
        - "templates/cloud_vpn/providers/rhel/responder/{{ cloud_vpn_responder_provider }}"
        - templates/cloud_vpn/providers/rhel/responder
  become: yes
  delegate_to: responder

- name: Restart IPSEC service
  systemd:
    name: ipsec
    state: restarted
  become: yes
  delegate_to: responder

- name: Enable IP forwarding
  command: /sbin/sysctl -w net.ipv4.ip_forward=1
  become: yes
  delegate_to: responder
